org: lbibera
app: headhuntr
service: api

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  tracing:
    apiGateway: true
    lambda: true


layers:
  python-shared:
    path: python-shared
    name: ${sls:stage}-python-shared
    description: Common libraries
    compatibleRuntimes:
      - python3.9
    compatibleArchitectures:
      - x86_64
      - arm64
    licenseInfo: GPLv3 # optional, a string specifying license information
    allowedAccounts: # optional, a list of AWS account IDs allowed to access this layer.
      - ${aws:accountId}
    retain: true

resources:
 Resources:
  PlatformAPIGateway:
     Type: AWS::ApiGateway::RestApi
     Properties:
       Name: ${sls:stage}-platform-api

 Outputs:
    apiGatewayRestApiId:
      Value:
        Ref: PlatformAPIGateway
      Export:
        Name: ${sls:stage}-PlatformAPIGateway-restApiId
 
    apiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt:
          - PlatformAPIGateway
          - RootResourceId
      Export:
        Name: ${sls:stage}-PlatformAPIGateway-rootResourceId
