org: lbibera
app: headhuntr
service: shared

frameworkVersion: '3'

provider:
  name: aws
  tracing:
    apiGateway: true
  deploymentBucket:
    name: ${self:custom.deploymentBucketName}
    serverSideEncryption: AES256

custom:
  deploymentBucketName: hhv2.deployment.artifacts

plugins:
  - serverless-deployment-bucket

layers:
  pythonshared:
    path: python-shared
    name: ${sls:stage}-python-shared
    description: Common libraries
    compatibleRuntimes:
      - python3.9
    compatibleArchitectures:
      - x86_64
      - arm64
    licenseInfo: GPLv3
    allowedAccounts:
      - ${aws:accountId}
    retain: true

resources:
 Resources:
  PlatformAPIGateway:
     Type: AWS::ApiGateway::RestApi
     Properties:
       Name: ${sls:stage}-platform-api

outputs:
  S3SharedBucketArtifactsName: ${self:custom.deploymentBucketName}
  ApiGatewayRestApiId: !Ref PlatformAPIGateway
  ApiGatewayRestApiRootResourceId: 
    Fn::GetAtt: [ PlatformAPIGateway, RootResourceId]