org: lbibera
app: headhuntr
service: shared

frameworkVersion: '3'

provider:
  name: aws
  tracing:
    apiGateway: true

layers:
  pythonshared:
    path: python-shared
    name: ${sls:stage}-python-shared
    description: Common libraries
    compatibleRuntimes:
      - python3.9
    compatibleArchitectures:
      - x86_64
      - arm64
    licenseInfo: GPLv3
    allowedAccounts:
      - ${aws:accountId}
    retain: true

resources:
 Resources:
  PlatformAPIGateway:
     Type: AWS::ApiGateway::RestApi
     Properties:
       Name: ${sls:stage}-platform-api

 Outputs:
    apiGatewayRestApiId:
      Value:
        Ref: PlatformAPIGateway
      Export:
        Name: sls-${self:service}-${sls:stage}-PlatformAPIGateway-restApiId
 
    apiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt:
          - PlatformAPIGateway
          - RootResourceId
      Export:
        Name: sls-${self:service}-${sls:stage}-PlatformAPIGateway-rootResourceId
        